#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Kind {
    String,
    Bool,
    Integer,
    Duration,
    List,
}

pub struct FlagSpec {
    pub name: &'static str,
    pub aliases: &'static [&'static str],
    pub env: &'static [&'static str],
    pub kind: Kind,
    pub default: Option<&'static str>,
    pub yaml: bool,
}

macro_rules! flags {
    ($(($name:literal, $kind:ident, $default:expr, [$($alias:literal),*], [$($env:literal),*], $yaml:literal)),* $(,)?) => {
        pub static FLAGS: &[FlagSpec] = &[$(FlagSpec { name: $name, kind: Kind::$kind, default: $default, aliases: &[$($alias),*], env: &[$($env),*], yaml: $yaml }),*];
    };
}

flags! {
    ("help", Bool, None, ["h"], [], false),
    ("version", Bool, None, ["v", "V"], [], false),
    ("short", Bool, None, ["s"], [], false),
    ("config", String, None, [], [], false),
    ("origincert", String, None, [], ["TUNNEL_ORIGIN_CERT"], true),
    ("credentials-file", String, None, ["cred-file"], ["TUNNEL_CRED_FILE"], true),
    ("credentials-contents", String, None, [], ["TUNNEL_CRED_CONTENTS"], true),
    ("token", String, None, [], ["TUNNEL_TOKEN"], true),
    ("token-file", String, None, [], ["TUNNEL_TOKEN_FILE"], true),
    ("protocol", String, Some("auto"), ["p"], ["TUNNEL_TRANSPORT_PROTOCOL"], true),
    ("post-quantum", Bool, Some("false"), ["pq"], ["TUNNEL_POST_QUANTUM"], true),
    ("features", List, None, ["F"], [], true),
    ("url", String, Some("http://127.0.0.1:8080"), [], ["TUNNEL_URL"], true),
    ("hello-world", Bool, Some("false"), [], ["TUNNEL_HELLO_WORLD"], true),
    ("unix-socket", String, None, [], ["TUNNEL_UNIX_SOCKET"], true),
    ("edge", List, None, [], ["TUNNEL_EDGE"], true),
    ("region", String, None, [], ["TUNNEL_REGION"], true),
    ("edge-ip-version", String, Some("auto"), [], ["TUNNEL_EDGE_IP_VERSION"], true),
    ("edge-bind-address", String, None, [], ["TUNNEL_EDGE_BIND_ADDRESS"], true),
    ("metrics", String, Some("localhost:0"), [], ["TUNNEL_METRICS"], true),
    ("ha-connections", Integer, Some("4"), [], [], true),
    ("grace-period", Duration, Some("30s"), [], ["TUNNEL_GRACE_PERIOD"], true),
    ("rpc-timeout", Duration, Some("5s"), [], [], true),
    ("write-stream-timeout", Duration, Some("0s"), [], ["TUNNEL_STREAM_WRITE_TIMEOUT"], true),
    ("dial-edge-timeout", Duration, Some("15s"), [], ["DIAL_EDGE_TIMEOUT"], true),
    ("retries", Integer, Some("5"), [], ["TUNNEL_RETRIES"], true),
    ("max-edge-addr-retries", Integer, Some("8"), [], [], true),
    ("quic-disable-pmtu-discovery", Bool, Some("false"), [], ["TUNNEL_DISABLE_QUIC_PMTU"], true),
    ("quic-connection-level-flow-control-limit", Integer, Some("31457280"), [], ["TUNNEL_QUIC_CONN_LEVEL_FLOW_CONTROL_LIMIT"], true),
    ("quic-stream-level-flow-control-limit", Integer, Some("6291456"), [], ["TUNNEL_QUIC_STREAM_LEVEL_FLOW_CONTROL_LIMIT"], true),
    ("no-prechecks", Bool, Some("false"), [], ["TUNNEL_NO_PRECHECKS"], true),
    ("no-autoupdate", Bool, Some("false"), [], ["NO_AUTOUPDATE"], true),
    ("autoupdate-freq", Duration, Some("24h"), [], [], true),
    ("pidfile", String, None, [], ["TUNNEL_PIDFILE"], true),
    ("disable-path-normalization", Bool, Some("true"), [], ["TUNNEL_DISABLE_PATH_NORMALIZATION"], true),
    ("proxy-connect-timeout", Duration, Some("30s"), [], [], true),
    ("proxy-tls-timeout", Duration, Some("10s"), [], [], true),
    ("proxy-tcp-keepalive", Duration, Some("30s"), [], [], true),
    ("proxy-no-happy-eyeballs", Bool, Some("false"), [], [], true),
    ("proxy-keepalive-connections", Integer, Some("100"), [], [], true),
    ("proxy-keepalive-timeout", Duration, Some("90s"), [], [], true),
    ("http-host-header", String, None, [], ["TUNNEL_HTTP_HOST_HEADER"], true),
    ("origin-server-name", String, None, [], ["TUNNEL_ORIGIN_SERVER_NAME"], true),
    ("origin-ca-pool", String, None, [], ["TUNNEL_ORIGIN_CA_POOL"], true),
    ("no-tls-verify", Bool, Some("false"), [], ["NO_TLS_VERIFY"], true),
    ("no-chunked-encoding", Bool, Some("false"), [], ["TUNNEL_NO_CHUNKED_ENCODING"], true),
    ("http2-origin", Bool, Some("false"), [], ["TUNNEL_ORIGIN_ENABLE_HTTP2"], true),
    ("loglevel", String, Some("info"), [], ["TUNNEL_LOGLEVEL"], true),
    ("transport-loglevel", String, Some("info"), ["proto-loglevel"], ["TUNNEL_PROTO_LOGLEVEL", "TUNNEL_TRANSPORT_LOGLEVEL"], true),
    ("logfile", String, None, [], ["TUNNEL_LOGFILE"], true),
    ("log-directory", String, None, [], ["TUNNEL_LOGDIRECTORY"], true),
    ("output", String, Some("default"), [], ["TUNNEL_MANAGEMENT_OUTPUT", "TUNNEL_LOG_OUTPUT"], true),
    ("trace-output", String, None, [], ["TUNNEL_TRACE_OUTPUT"], true),
    ("json", String, None, ["j"], ["TUNNEL_INGRESS_VALIDATE_JSON"], false),
    ("hostname", String, None, [], ["TUNNEL_HOSTNAME"], true),
    ("name", String, None, ["n"], ["TUNNEL_NAME"], true),
    ("id", String, None, [], ["TUNNEL_ID"], true),
    ("lb-pool", String, None, [], ["TUNNEL_LB_POOL"], true),
    ("api-url", String, Some("https://api.cloudflare.com/client/v4"), [], ["TUNNEL_API_URL"], true),
    ("api-key", String, None, [], ["TUNNEL_API_KEY"], true),
    ("api-email", String, None, [], ["TUNNEL_API_EMAIL"], true),
    ("api-ca-key", String, None, [], ["TUNNEL_API_CA_KEY"], true),
    ("cacert", String, None, [], ["TUNNEL_CACERT"], true),
    ("tag", List, None, [], ["TUNNEL_TAG"], true),
    ("label", String, None, [], [], true),
    ("quick-service", String, Some("https://api.trycloudflare.com"), [], [], true),
    ("allowed-mail", List, None, [], [], true),
    ("management-diagnostics", Bool, Some("true"), [], ["TUNNEL_MANAGEMENT_DIAGNOSTICS"], true),
    ("management-hostname", String, Some("management.argotunnel.com"), [], ["TUNNEL_MANAGEMENT_HOSTNAME"], true),
    ("service-op-ip", String, Some("198.41.200.113:80"), [], ["TUNNEL_SERVICE_OP_IP"], true),
    ("max-fetch-size", Integer, None, [], ["TUNNEL_MAX_FETCH_SIZE"], true),
    ("icmpv4-src", String, None, [], ["TUNNEL_ICMPV4_SRC"], false),
    ("icmpv6-src", String, None, [], ["TUNNEL_ICMPV6_SRC"], false),
    ("max-active-flows", Integer, None, [], ["TUNNEL_MAX_ACTIVE_FLOWS"], false),
    ("dns-resolver-addrs", List, None, [], ["TUNNEL_DNS_RESOLVER_ADDRS"], false),
    ("socks5", Bool, None, [], ["TUNNEL_SOCKS"], true),
    ("bastion", Bool, None, [], ["TUNNEL_BASTION"], true),
    ("ssh-server", Bool, None, [], ["TUNNEL_SSH_SERVER"], true),
    ("local-ssh-port", String, Some("2222"), [], ["LOCAL_SSH_PORT"], true),
    ("ssh-idle-timeout", Duration, None, [], ["SSH_IDLE_TIMEOUT"], true),
    ("ssh-max-timeout", Duration, None, [], ["SSH_MAX_TIMEOUT"], true),
    ("proxy-address", String, Some("127.0.0.1"), [], ["TUNNEL_PROXY_ADDRESS"], true),
    ("proxy-port", Integer, Some("0"), [], ["TUNNEL_PROXY_PORT"], true),
    ("proxy-connection-timeout", Duration, Some("90s"), [], [], true),
    ("proxy-expect-continue-timeout", Duration, Some("90s"), [], [], true),
    ("proxy-dns", Bool, None, [], [], true),
    ("proxy-dns-port", Integer, None, [], [], true),
    ("proxy-dns-address", String, None, [], [], true),
    ("proxy-dns-upstream", List, None, [], [], true),
    ("proxy-dns-max-upstream-conns", Integer, None, [], [], true),
    ("proxy-dns-bootstrap", List, None, [], [], true),
    ("no-update-service", Bool, None, [], [], false),
    ("force", Bool, None, ["f"], [], false),
    ("beta", Bool, None, [], [], false),
    ("staging", Bool, None, [], [], false),
    ("show-deleted", Bool, None, ["d"], [], false),
    ("sort-by", String, None, [], [], false),
    ("invert-sort", Bool, None, [], [], false),
    ("show-recently-disconnected", Bool, None, [], [], false),
    ("name-prefix", String, None, [], [], false),
    ("exclude-prefix", String, None, [], [], false),
    ("overwrite-dns", Bool, None, [], [], false),
    ("connector-id", String, None, ["c"], [], false),
    ("resource", String, None, [], [], false),
    ("diag-container-id", String, None, [], [], false),
    ("diag-pod-id", String, None, [], [], false),
    ("no-diag-logs", Bool, None, [], [], false),
    ("no-diag-metrics", Bool, None, [], [], false),
    ("no-diag-system", Bool, None, [], [], false),
    ("no-diag-runtime", Bool, None, [], [], false),
    ("no-diag-network", Bool, None, [], [], false),
    ("secret", String, None, [], [], false),
    ("loginURL", String, Some("https://dash.cloudflare.com/argotunnel"), [], [], false),
    ("callbackURL", String, Some("https://login.cloudflareaccess.org/"), [], [], false),
    ("fedramp", Bool, None, [], [], false),
    ("default", Bool, None, [], [], false),
    ("is-default", Bool, None, [], [], false),
    ("comment", String, None, [], [], false),
    ("exclude-name-prefix", String, None, ["enp"], [], false),
    ("when", String, None, ["w"], [], false),
    ("filter-is-deleted", Bool, None, [], [], false),
    ("filter-tunnel-id", String, None, [], [], false),
    ("filter-network-is-subset-of", String, None, ["nsub"], [], false),
    ("filter-network-is-superset-of", String, None, ["nsup"], [], false),
    ("filter-comment-is", String, None, [], [], false),
    ("filter-vnet-id", String, None, [], [], false),
}

pub fn find(name: &str) -> Option<&'static FlagSpec> {
    FLAGS
        .iter()
        .find(|flag| flag.name == name || flag.aliases.contains(&name))
}
